version: '3.8'
services:
  db:
    image: postgres:14.1-alpine
    restart: always
    env_file:
      - .env
    healthcheck:
      test: ["CMD-SHELL", "pg_isready", "-d", "db_prod"]
      interval: 30s
      timeout: 60s
      retries: 5
      start_period: 80s
    ports:
      - '3000:5432'
    container_name: international_db
    volumes:
      - db:/var/lib/postgresql/data
volumes:
  db:
    driver: local

# docker-compose -f docker-compose-postgres.yaml up